<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <Version>0.1.1</Version>
    <AssemblyInformationalVersion>0.1.1</AssemblyInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConstrainCert.Core\ConstrainCert.Core.csproj" />
  </ItemGroup>
</Project>

